### ISSUE TITLE
Not running 

### ISSUE THREAD

**Issue by HyperUpscale** [samilao101/docchatbot#1]
(docchatbot) D:\TRIAL\docchatbot>python main.py
Traceback (most recent call last):
  File "D:\TRIAL\docchatbot\main.py", line 14, in <module>
    file_content = file.read()
  File "C:\Users\super\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5381: character maps to <undefined>

**Comment by samilao101** [comment]
This should help I think:
import chardet

with open(file_path, 'rb') as file:
    result = chardet.detect(file.read())

encoding = result['encoding']

with open(file_path, 'r', encoding = encoding) as file:
    file_content = file.read()

**Comment by HyperUpscale** [comment]
I don't know why only few people are providing the full code or full instructions...

here is the code

1. git clone https://github.com/samilao101/docchatbot.git

2.  python -m venv docchatbot

3. docchatbot\Scripts\activate.bat

4. cd docchatbot

5. `pip install streamlit openai python-dotenv streamlit_chat chardet` #Here are the installation retirements

6. Here is the fixed code (without the full API key)
"
import streamlit as st
import os
import openai
import chardet
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = "sk-???"
openai.api_key = OPENAI_API_KEY

file_path = 'GSARs.txt'

# Detecting file encoding
with open(file_path, 'rb') as file:
    result = chardet.detect(file.read())
    encoding = result['encoding']

# Reading the file with the detected encoding
with open(file_path, 'r', encoding=encoding) as file:
    file_content = file.read()

st.image("cumminslogo.png")
st.header("GSAR Documentation Helper")

prompt = st.text_input(
    "Please type your GSAR questions below. Questions/Responses may be monitored.", placeholder="Enter prompt...")

if "user_prompt_history" not in st.session_state:
    st.session_state["user_prompt_history"] = []

if "chat_answers_history" not in st.session_state:
    st.session_state["chat_answers_history"] = []

if prompt:
    gsar_prompt = f"Use the following context below to answer question '{prompt}' (Please use markdown to make the response easier to read). Do not make up answers and only respond to questions relevant to the context.\n\nContext: {file_content}"

    with st.spinner("Generating response..."):
        generated_response = openai.ChatCompletion.create(
            model='gpt-3.5-turbo',
            messages=[
                {"role": "user", "content": gsar_prompt}
            ],
            temperature=0.0
        )

        formatted_response = generated_response['choices'][0]['message']['content']
        print(formatted_response)

        st.session_state["user_prompt_history"].append(prompt)
        st.session_state["chat_answers_history"].append(formatted_response)

if st.session_state["chat_answers_history"]:
    for generated_response, user_query in zip(st.session_state["chat_answers_history"], st.session_state["user_prompt_history"]):
        st.write(generated_response)
"


7. `streamlit run main.py`      <---- and here is how to run the code


It is not so hard to do.

**Comment by HyperUpscale** [comment]
[fixed.TXT](https://github.com/samilao101/docchatbot/files/12838391/fixed.TXT)

I don't know why only few people are providing the full code or full instructions...

here is the code

1. git clone https://github.com/samilao101/docchatbot.git

2.  python -m venv docchatbot

3. docchatbot\Scripts\activate.bat

4. cd docchatbot

5. `pip install streamlit openai python-dotenv streamlit_chat chardet` #Here are the installation retirements

6. Here is the fixed code (without the full API key)
attached TXT file 


7. `streamlit run main.py`      <---- and here is how to run the code


It is not so hard to add the steps  `¯\_(シ)_/¯`
